Changing libs version 2

diff --git a/.github/workflows/CI-evaluation.yaml b/.github/workflows/CI-evaluation.yaml
--- a/.github/workflows/CI-evaluation.yaml
+++ b/.github/workflows/CI-evaluation.yaml
@@ -109,13 +109,13 @@ jobs:
       # Checa vulnerabilidades críticas no Trivy SCA e gosec (fail if found)
       - name: Fail on Critical Vulnerabilities (SCA & SAST)
         run: |
-          CRIT_TRIVY=$(jq '[.Results[].Vulnerabilities[] | select(.Severity=="CRITICAL")] | length' trivy-sca-results.json)
+          CRIT_TRIVY=$(jq '[.Results[].Vulnerabilities // [] | .[] | select(.Severity=="CRITICAL")] | length' trivy-sca-results.json)
           CRIT_GOSEC=$(jq '[.Issues[] | select(.severity=="HIGH")] | length' evaluation-service/gosec-results.json)
           echo "Criticals in Trivy SCA: $CRIT_TRIVY"
           echo "Criticals in gosec (HIGH): $CRIT_GOSEC"
           if [ "$CRIT_TRIVY" != "0" ] || [ "$CRIT_GOSEC" != "0" ]; then
-            echo "Critical vulnerabilities found! Failing pipeline."
-            exit 1
+          echo "Critical vulnerabilities found! Failing pipeline."
+          exit 1
           fi
 
         # Upload Trivy scan results as artifact
